### PR TITLE
remove dependencies on git pcap and gyp

### PR DESCRIPTION
**Pull request by mkellsy**
I changed the homespun dep to only the utilities. This removes the arp-a dep and no build when installing. It also removed the need for libpcpap-dev requirement.

I also removed the unnecessary community types github dep, it wasn't being used. This removed the dependency on git.

I don't have a honeywell thermostat, so you will need to test this. (I have an ecobee)

### CODE REVIEW

**Comment by d0n4v4nb3ck3r** [comment]
I will test this when I get home too!

**Comment by donavanbecker** [comment]
@mkellsy I have published this on npm as beta, and this is what I get when I try to install
```
ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-31T03_49_31_490Z-debug.log
root@raspberrypi:/home/pi# npm install -g --unsafe-perm homebridge@latest homebridge-config-ui-x@latest homebridge-honeywell-home@2.1.0-beta1
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/homespun/hap-nodejs-community-types.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-31T03_50_12_158Z-debug.log
```

**Comment by mkellsy** [comment]
Homespun's dependencies are all over the place. I reduced it to just what you are using, but the homespun-utilities package still has a git reference.
```json
  "dependencies": {
    "glob": "^7.0.6",
    "hap-nodejs-community-types": "git+https://github.com/homespun/hap-nodejs-community-types.git",
    "pluralize": "3.0.0",
    "underscore": "1.8.3"
  },
```

What we need to do is, move the one utility you are using `roundTrip` to this project and get rid of homespun.

**Comment by donavanbecker** [comment]
This is published on npm, can't that just be changed under the dependencies? or am i wrong?
[hap-nodejs-community-types](https://www.npmjs.com/package/hap-nodejs-community-types)

**Comment by mkellsy** [comment]
Your plugin doesn't even use community types you don't need it.

**Comment by mkellsy** [comment]
This pull request is updated with the new roundtrip.js file and homespun removed.

Test again.

**Comment by donavanbecker** [comment]
Sorry @mkellsy this is what I get for the output
```
12/31/2019, 04:24:13] Error: The requested platform 'homebridge-honeywell-home.HoneywellHome' was not registered by any plugin.
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:140:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
[12/31/2019, 04:24:13] Got SIGTERM, shutting down Homebridge...
homebridge.service: Main process exited, code=exited, status=143/n/a
homebridge.service: Failed with result 'exit-code'.
homebridge.service: Service RestartSec=3s expired, scheduling restart.
homebridge.service: Scheduled restart job, restart counter is at 4.
Stopped Homebridge.
Started Homebridge.
[12/31/2019, 04:24:23] Loaded config.json with 0 accessories and 4 platforms.
[12/31/2019, 04:24:23] ---
[12/31/2019, 04:24:23] Loaded plugin: homebridge-config-ui-x
[12/31/2019, 04:24:23] Registering platform 'homebridge-config-ui-x.config'
[12/31/2019, 04:24:23] ---
[12/31/2019, 04:24:23] Loaded plugin: homebridge-ecoplug
[12/31/2019, 04:24:23] Registering platform 'homebridge-ecoplugs.EcoPlug'
[12/31/2019, 04:24:23] ---
[12/31/2019, 04:24:23] ====================
[12/31/2019, 04:24:23] ERROR LOADING PLUGIN homebridge-honeywell-home:
[12/31/2019, 04:24:23] Error: Cannot find module 'lib/roundtrip'
Require stack:
- /usr/lib/node_modules/homebridge-honeywell-home/index.js
- /usr/lib/node_modules/homebridge/lib/plugin.js
- /usr/lib/node_modules/homebridge/lib/server.js
- /usr/lib/node_modules/homebridge/lib/cli.js
- /usr/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-honeywell-home/index.js:7:19)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
[12/31/2019, 04:24:23] ====================
[12/31/2019, 04:24:25] Loaded plugin: homebridge-ring
[12/31/2019, 04:24:25] Registering platform 'homebridge-ring.Ring'
[12/31/2019, 04:24:25] ---
[12/31/2019, 04:24:25] Loading 4 platforms...
[12/31/2019, 04:24:25] [Config] Initializing config platform...
[12/31/2019, 04:24:25] [Config] Running in Standalone Mode.
[12/31/2019, 04:24:25] [Ring] Initializing Ring platform...
[12/31/2019, 04:24:25] [EcoPlug] Initializing EcoPlug platform...
[12/31/2019, 04:24:25] Error: The requested platform 'homebridge-honeywell-home.HoneywellHome' was not registered by any plugin.
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:140:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
```

**Comment by donavanbecker** [comment]
also can homebridge-honeywell-home.HoneywellHome, just be Honeywell-home? or honeywellhome instead of everything like that? is that possible?

Thanks for doing all this!

**Comment by mkellsy** [comment]
I will look at the issue tomorrow. I am working on HOOBS instance support.

**Comment by d0n4v4nb3ck3r** [comment]
Thanks

**Comment by donavanbecker** [comment]
@mkellsy Thanks!

**Comment by mkellsy** [comment]
The roundtrip require is fixed.

**Comment by mkellsy** [comment]
Homebridge requires that your plugin starts with "homebridge-". So the "homebridge-honeywell-home.HoneywellHome" is the package plus the alias.

Since I am helping with this plugin the guys at HOOBS want to certify it for HOOBS. It will simply be called Honeywell in HOOBS. (@hoobs/honeywell)

Go ahead and test this again.

**Comment by donavanbecker** [comment]
@mkellsy I was able to get this installed! So much easier to install then before!! I am totally okay with it being called @hoobs/honeywell!! I am going to merge this and release 2.1.0

This is read-only right now so I will change that in the readme. Has never had write to the thermostat support.

**Pull request merged**
